titleId <- spectatorReuse[c("estc_id", "title")] %>% distinct(estc_id, .keep_all = TRUE)

search_title <- function(regex) {
  return(titleId[grepl(regex, tolower(titleId$title)),])
}

# Some manual works grouping
list_of_prominent_titles <- c(
  "addison",
  "the beauties of the spec",
  "notes upon",
  "paradise lost",
  "poetical work",
  "young gentleman",
  "polite preceptor",
  "moral miscellany",
  "evidences",
  "dictionary",
  "pleasing instructor",
  "a collection from the spec",
  "collection of english",
  "collection of select",
  "histories, fables",
  "collection of prose",
  "leisure hours",
  "maxims, observations, and reflection",
  "les beau",
  "christian magazine",
  "collection in prose",
  "works of the english",
  "elegant extracts",
  "system of divinity",
  "polite instructor",
  "lessons in elocution",
  "young englishman",
  "matrimonial preceptor",
  "works of the poets",
  "speaker",
  "belles lettres",
  "beauties of eminent",
  "select english",
  "beauties of english prose",
  "collection of several stories",
  "essays on education",
  "english miscellanies",
  "correspondent",
  "making abridgements",
  "complete english scholar",
  "lessons in reading",
  "rev. m. moreton",
  "lesebuch",
  "general enternainer",
  "nunnery of coquettes",
  "bee reviv'd",
  "help to elocution",
  "ladies magazine",
  "mentor",
  "new story-teller",
  "tractate of education",
  "beauties of history",
  "genteleman's library",
  "art of letter-writing",
  "whimsical mr.spectator",
  "allegories and visions",
  "polite epistolary",
  "town and country",
  "essays of suicide",
  "beauties of milton",
  "revolution-principles",
  "edinburgh repo",
  "english reader",
  "elements of elocution",
  "ladies complete letter-writer",
  "female orators",
  "history of the reign",
  "christian's consolations",
  "family library",
  "sermons to young men",
  "american spec",
  "prose epitome",
  "american selection",
  "school of wisdom",
  "history of europe",
  "richard steele",
  "beautiful extracts",
  "henry grove",
  "britannica",
  "golden manual",
  "miscellanies in prose",
  "gardener's recreation",
  "poems on several",
  "dear variety",
  "dictionnaire",
  "philosophy of medicine",
  "history of tom jones",
  "poets of great britain",
  "european magazine",
  "christian hero",
  "elements of reading",
  "parliamentary debates",
  "four sermons",
  "weekly entertainer",
  "instructive letter-writer",
  "lessons in prose",
  "present for a son",
  "the works",
  "novelist's magazine",
  "essay on anger",
  "chirurgical treatise",
  "gentleman and lady's polite",
  "mottoes of the spec",
  "observations upon liberal",
  "medical extracts",
  "columbian library",
  "beauties of the poets",
  "beauties in prose",
  "art or reading",
  "miscellanea nova",
  "poem of the last",
  "theodosius and constantia",
  "literary bouquet",
  "anecdotes, memoirs",
  "modern story teller",
  "horace",
  "sentiments on education",
  "principles of elocution",
  "quadriennium",
  "ichnographia",
  "chinese tales",
  "paradisus",
  "moral philosophy",
  "mirrour",
  "britannic magazine",
  "tell-tale",
  "universal story-teller",
  "lilliputian",
  "collection of modern",
  "rhetorical grammar",
  "occasional miscellany",
  "grammatical exercises",
  "poetical preceptor",
  "agreeable companion",
  "virgil",
  "female reader",
  "sacred poems",
  "essay toward fixing",
  "orator",
  "military magazine",
  "english preacher",
  "genuine works",
  "moral instructions",
  "poetry made familiar",
  "historical mirror",
  "poems by john milton",
  "bible",
  "english grammar",
  "introduction to reading",
  "royal letter writer",
  "seaven sermons",
  "roach's beauties",
  "divine hymns",
  "seraph",
  "moral and physical",
  "entertaining humorist",
  "poems on various",
  "odes",
  "prose miscellany",
  "essay on the art of reading",
  "poems on several",
  "art of writing love",
  "english exercises",
  "amusing instructor",
  "books of psalms",
  "promote piety",
  "system of philology",
  "accomplished tutor",
  "messiah",
  "sacred literature",
  "royal american",
  "modern gardening",
  "collection of apothegms",
  "state of the republic",
  "wonderful story teller",
  "seventeen sermons",
  "moral and instructive",
  "collection of the sermons",
  "john tillotson",
  "religious sentiments",
  "thomas parnell",
  "dictionary of arts and sciences",
  "new-year's-gift"
)


distinct_titles <- spectatorReuse %>% distinct(estc_id, .keep_all = TRUE) %>% group_by(title) %>% dplyr::summarise(n = n())

## Searching distinct titles from reuse data and only using the most prominent one to see if the weigths of character reuse shift since there are not
## so many editions of the same book. Of course you can't say that having multiple editions of same book does not represent anything, but this is an interesting
## comparison point. 
## This is not perfect. Many titles are used multiple times, but this will make the differents considerably smaller
distinct_reuse_entries <- spectatorReuse %>% group_by(title, estc_id) %>%
  dplyr::summarise(sum = sum(length)) %>% ungroup() %>% group_by(title) %>% filter(sum == max(sum)) %>% ungroup() %>%
  distinct(estc_id, .keep_all = TRUE)

under5000_entries <- spectatorReuse %>% group_by(estc_id) %>% 
  dplyr::summarise(reuse_sum = sum(length)) %>% filter(reuse_sum < 5000)
